name: Lint and Test

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: |
          uv sync --all-extras --dev
          uv add pytest-html flake8 flake8-html

      - name: Run linting with Black
        run: uv run black . --check --diff

      - name: Create report directories
        run: |
          mkdir -p reports/flake8
          mkdir -p reports/pytest
          
      - name: Run flake8 linting with HTML report
        run: uv run flake8 --format=html --htmldir=reports/flake8 --exclude=.venv,.git,__pycache__,build,dist .
        continue-on-error: true

      - name: Run tests with HTML report
        run: uv run pytest tests --html=reports/pytest/report.html --self-contained-html
        continue-on-error: true

      - name: Check if reports exist
        run: |
          ls -la reports/
          ls -la reports/pytest || echo "pytest reports directory is empty"
          ls -la reports/flake8 || echo "flake8 reports directory is empty"
          touch reports/pytest/index.html || mkdir -p reports/pytest && touch reports/pytest/index.html
          touch reports/flake8/index.html || mkdir -p reports/flake8 && touch reports/flake8/index.html

      - name: Upload test report
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          name: pytest-report
          path: reports/pytest
          retention-days: 14

      - name: Upload lint report
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          name: flake8-report
          path: reports/flake8
          retention-days: 14